### ISSUE TITLE
Umgebungsvariable Linux/OSX

### ISSUE THREAD

**Issue by maxfunke** [angular-schule/2017-05-aspnetcore-angular-ddf#2]
Nur damit es nicht untergeht fürs nächste mal:

für Linux und OSX heißt der Befehl `export`, statt `set`
```
export ASPNETCORE_ENVIRONMENT=Development
dotnet run
```

**Comment by fmalcher** [comment]
Vielen Dank! Ich habs ins README übertragen 😎

**Comment by JohannesHoppe** [comment]
:+1:
